# server
server:
  port: 8080
  servlet:
    context-path: /

# logging
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO

# postgresql
spring:
  datasource:
    hikari:
      #hikari.maximum-pool-size: 4
      jdbc-url: jdbc:postgresql://localhost:5432/eng_word
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver

# mybatis
#mybatis:
#  type-aliases-package: com.eng.word.dao
#  mapper-locations: classpath:/mapper/**/*.xml
#  configuration.map-underscore-to-camel-case: true
